# BINGO!

## Requirements

* Create a class `Bingo` that is initialized into a specific game
* That `bingo` game can add new players with the `add_player` method
* The players will be added to the attribute `players`, storing their names
* The players boards will be 2D arrays (you can use numpy but it is not necessary) consisting of numbers from 0 to 99 and of size (3X5). Its numbers must be assigned randomly.
* The player boards (and current state) will be saved into the attribute  `player_boards` as values of `player_name` key
* The initialized class `bingo` must have a `play_round` method that throws a random number and check whether or not the players have it 
* A player gets 10 points for every point got
* A player gets 150 points if that player is the first one to have a row
* A player gets 150 points if that player is the first one to have a column
* A player gets 250 points if that player is the first one to complete the bingo. Once this happens the game is finished and you can show the ranking.


REMEMBER:

* Numbers must be random and from 0 - 99
* Once a number has appeared it can not appear again

In [12]:
import random
from numpy.random import default_rng
import numpy as np

class Bingo():
    def __init__(self):
        self.player_boards = {}
        self.player_points = {}
        self.player_board_control = {}
        self.number_recorded = []
        print("Bingo game has started, good luck!\nWaiting for users to join...")
        
    def add_player_board(self, player):
        rng = default_rng()
        player_board = rng.choice(100, size = (3,5), replace=False)
        self.player_boards[player] = player_board
        self.player_points[player] = 0
        self.player_board_control[player] = np.zeros((3,5))
        self.row_ctrl = 0
        self.column_ctrl = 0
        print(f"{player} has joined the game!")
        print(f"Welcome {player}, here's your game board:\n{self.player_boards[player]}\nGood luck!")
    
    def show_rankings(self):
        for name, values in self.player_boards.items():
            print(f"{name} has {self.player_points[name]} points!")
        
    
    def check_bingo(self):
        for name, values in self.player_boards.items():
            s = 0
            for i in range(np.array(self.player_board_control[name]).shape[0]):
                        for j in range(np.array(self.player_board_control[name]).shape[1]):
                            s = s + self.player_board_control[name][i][j]
                            
            if s == -(np.array(self.player_board_control[name]).shape[0] * np.array(self.player_board_control[name]).shape[1]):
                self.player_points[name] += 250
                print("------------------------------------")
                print(f"BINGO! {name} has made it and gets 250 points. Well done!")
                self.show_rankings()
                break
                                    
    def play_round(self):
        if len(self.number_recorded) < 1:
            print("Bingo Game Is Starting. Good Luck Everyone!")
        
        while True:
            number = random.randint(0,99)
            if number in self.number_recorded:
                continue
            else:
                break   
        self.number_recorded.append(number)
        print(f"The lucky number for this round is: {number}")
        
        for name, values in self.player_boards.items():
            if number in values:
                for i in range(np.array(self.player_boards[name]).shape[0]):
                    for j in range(np.array(self.player_boards[name]).shape[1]):
                        if self.player_boards[name][i][j] == number:
                            self.player_board_control[name][i][j] = -1      
                self.player_points[name] += 10
                print(f"{name} has the number {number} and gets 10 points. Congrats!")    
                       
                for i in range(np.array(self.player_boards[name]).shape[0]):
                    for j in range(np.array(self.player_boards[name]).shape[1]):
                        if (np.array(self.player_board_control[name]).sum(axis = 0)[j] == -(np.array(self.player_boards[name]).shape[0])  
                        and self.column_ctrl == 0):                            
                            self.player_points[name] += 150
                            self.column_ctrl = 1
                            print(f"{name} is the first one who completes the column and gets 150 points. Conguratulations!")
                        elif (np.array(self.player_board_control[name]).sum(axis = 1)[i] == -(np.array(self.player_boards[name]).shape[1])
                        and self.row_ctrl == 0):
                            self.player_points[name] += 150
                            self.row_ctrl = 1
                            print(f"{name} is the first one who completes the row and gets 150 points. Conguratulations!")
        self.check_bingo()     

In [3]:
#Initialize the class and start the game!
bingo = Bingo()

Bingo game has started, good luck!
Waiting for users to join...


In [4]:
#Adding new players to the game
bingo.add_player_board("Cenk")

Cenk has joined the game!
Welcome Cenk, here's your game board:
[[62 50 68 82  9]
 [44 89 56 11 49]
 [92 34 61 74 52]]
Good luck!


In [5]:
bingo.add_player_board("Javi")

Javi has joined the game!
Welcome Javi, here's your game board:
[[77 78 23 59  1]
 [54 89 52 19 87]
 [72 32 14 20 12]]
Good luck!


In [6]:
bingo.add_player_board("Muhammed")

Muhammed has joined the game!
Welcome Muhammed, here's your game board:
[[ 4 75 34 83 20]
 [24 10 33 79 76]
 [73 31 28  7 17]]
Good luck!


In [7]:
bingo.add_player_board("Halimat")

Halimat has joined the game!
Welcome Halimat, here's your game board:
[[83 47 79 93 97]
 [15  0 57 38 78]
 [92 27 62 11 39]]
Good luck!


In [8]:
#Draw a number from the pot
bingo.play_round()

Bingo Game Is Starting. Good Luck Everyone!
The lucky number for this round is: 29


In [9]:
bingo.player_points

{'Cenk': 0, 'Javi': 0, 'Muhammed': 0, 'Halimat': 0}

In [10]:
bingo.player_board_control

{'Cenk': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'Javi': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'Muhammed': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 'Halimat': array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])}

In [11]:
bingo.player_boards

{'Cenk': array([[62, 50, 68, 82,  9],
        [44, 89, 56, 11, 49],
        [92, 34, 61, 74, 52]], dtype=int64),
 'Javi': array([[77, 78, 23, 59,  1],
        [54, 89, 52, 19, 87],
        [72, 32, 14, 20, 12]], dtype=int64),
 'Muhammed': array([[ 4, 75, 34, 83, 20],
        [24, 10, 33, 79, 76],
        [73, 31, 28,  7, 17]], dtype=int64),
 'Halimat': array([[83, 47, 79, 93, 97],
        [15,  0, 57, 38, 78],
        [92, 27, 62, 11, 39]], dtype=int64)}